### PR TITLE
Adds Vite 5 support

### PR DESCRIPTION
**Pull request by BALOTIAS**
Aloha! 🌺 I just did some virtual hula dancing to add Vite 5 support. I've thrown it in there like confetti at a beach party. Take a peek and give it a whirl! Test it out, and fingers crossed, it should be smoother than a surfing penguin. 🐧🏄‍♂️ Let me know how it grooves! 🤙

Had to add skipLibCheck to tsconfig.json because of:
* https://github.com/vitest-dev/vitest/issues/4567
* https://github.com/vitejs/vite/issues/15714

Looks like the type definitions from Vite 5 are doing the Macarena when they should be doing the Cha-Cha. Can you figure out the dance floor drama? Maybe they're just having a wild party and need a sober code enforcer. Any insights on their dance moves? 💃🕺 Let me know if you can help me make sense of this dance-off! 🕵️‍♂️🎉

### CODE REVIEW

**Comment by fabio-ivona** [comment]
+1 for the PR text :rofl: 

thanks @BALOTIAS for your work :heart: 

could you just check if we can make node 14.x tests pass or we should tag a new major version dropping its support?

**Comment by BALOTIAS** [comment]
@fabio-ivona :)) Vite 5 dropped support for old Nodejs versions, so 18, 20+ is required... see: https://vitejs.dev/blog/announcing-vite5#node-js-support

**Comment by fabio-ivona** [comment]
@BALOTIAS I've tagged [2.0.0-alpha.2](https://www.npmjs.com/package/@defstudio/vite-livewire-plugin/v/2.0.0-alpha.2)

would you mind to help me with some test before issuing with a stable release?

**Comment by BALOTIAS** [comment]
Sure, what exactly would you like to test?

**Comment by fabio-ivona** [comment]
Just if all works smoothly on your projects, in case there are some edge cases that aren't covered

**Comment by mikewink** [comment]
I installed the alpha 2 in a project and so far, it all works as expected, or how I used to work with the plugin before. As I will work on the Livewire project all week long, I will have plenty of hours to test.

**Comment by fabio-ivona** [comment]
Ok, I'm planning a stable release on next week, so we can fully test it. Thanks!

**Comment by mikewink** [comment]
I used the plugin in every day for several hours the last week. I had zero problems with it. It just works. 

I am running it inside a DDEV container, where the Vite config is a bit different from regular Laravel and it still works.

**Comment by fabio-ivona** [comment]
@mikewink thanks for your feedback ❤️

**Pull request merged**
